[colors]
background = '#262427'
foreground = '#fcfcfa'
selection-background = '#fcfcfa'
selection-foreground = '#262427'
cursor = '#fcfcfa'
black = '#262427'
red = '#ff7272'
green = '#bcdf59'
yellow = '#ffca58'
blue = '#49cae4'
magenta = '#a093e2'
cyan = '#aee8f4'
white = '#fcfcfa'
light_black = '#545452'
light_red = '#ff8787'
light_green = '#c6e472'
light_yellow = '#ffd271'
light_blue = '#64d2e8'
light_magenta = '#aea3e6'
light_cyan = '#baebf6'
light_white = '#fcfcfa'
