[colors]
background = '#101116'
foreground = '#d13554'
selection-background = '#c7ddfc'
selection-foreground = '#000000'
cursor = '#9bfca8'
black = '#101116'
red = '#ea3356'
green = '#64d98c'
yellow = '#faf968'
blue = '#306fb1'
magenta = '#ba3ec1'
cyan = '#59c2c6'
white = '#c7c7c7'
light_black = '#686868'
light_red = '#ed776d'
light_green = '#8df77a'
light_yellow = '#fefc7f'
light_blue = '#6a71f6'
light_magenta = '#ae40e4'
light_cyan = '#8efafd'
light_white = '#ffffff'
