[colors]
background = '#000000'
foreground = '#c7c7c7'
selection-background = '#c7ddfc'
selection-foreground = '#000000'
cursor = '#c7c7c7'
black = '#171717'
red = '#ea5386'
green = '#b3e153'
yellow = '#e4da81'
blue = '#4192d3'
magenta = '#8f3ef6'
cyan = '#6cb4d5'
white = '#c7c7c7'
light_black = '#686868'
light_red = '#ea86ac'
light_green = '#c5e280'
light_yellow = '#fdf38f'
light_blue = '#55bbf9'
light_magenta = '#b9a0f9'
light_cyan = '#7fd4fb'
light_white = '#ffffff'
