[colors]
background = '#121521'
foreground = '#d7dbea'
selection-background = '#34504b'
selection-foreground = '#dce0ee'
cursor = '#40786f'
black = '#262c45'
red = '#d96048'
green = '#7cab7f'
yellow = '#eeb64e'
blue = '#5d6bef'
magenta = '#7a729a'
cyan = '#ca8cbe'
white = '#dde0ed'
light_black = '#212840'
light_red = '#c47768'
light_green = '#8f9d90'
light_yellow = '#e4c693'
light_blue = '#5d85c6'
light_magenta = '#967de7'
light_cyan = '#c57eb3'
light_white = '#fdf6e3'
