[colors]
background = '#f8f9fb'
foreground = '#3e4a77'
selection-background = '#d4e8de'
selection-foreground = '#333c61'
cursor = '#386a51'
black = '#212840'
red = '#8f564b'
green = '#5c705b'
yellow = '#b36f00'
blue = '#40567a'
magenta = '#775d93'
cyan = '#8a5a7e'
white = '#d7dbea'
light_black = '#212840'
light_red = '#bd533e'
light_green = '#79957b'
light_yellow = '#f3b550'
light_blue = '#6988bc'
light_magenta = '#7b7393'
light_cyan = '#a4879c'
light_white = '#d7dbea'
