[colors]
background = '#242424'
foreground = '#ffffff'
selection-background = '#ffffff'
selection-foreground = '#242424'
cursor = '#ffffff'
black = '#242424'
red = '#e2425d'
green = '#66b238'
yellow = '#dec541'
blue = '#54aad0'
magenta = '#e8b2f8'
cyan = '#5abf9b'
white = '#e6e6e6'
light_black = '#616161'
light_red = '#ec5b58'
light_green = '#6bd162'
light_yellow = '#e9e85c'
light_blue = '#78c3f3'
light_magenta = '#f2afee'
light_cyan = '#6adcc5'
light_white = '#ffffff'
