[colors]
background = '#1d1e1d'
foreground = '#ffffff'
selection-background = '#3f638a'
selection-foreground = '#ffffff'
cursor = '#9d9d9d'
black = '#000000'
red = '#c65339'
green = '#6ac44b'
yellow = '#b8b74a'
blue = '#6444ed'
magenta = '#d357db'
cyan = '#69c1cf'
white = '#d1d1d1'
light_black = '#909090'
light_red = '#eb5a3a'
light_green = '#77ea51'
light_yellow = '#efef53'
light_blue = '#d09af9'
light_magenta = '#eb5af7'
light_cyan = '#78f1f2'
light_white = '#ededed'
