# Adwaita
[colors]
foreground = "#000000"
background = "#ffffff"
cursor_bg = "#000000"
cursor_border = "#000000"
cursor_fg = "#ffffff"
selection_bg = "#c0bfbc"
selection_fg = "#000000"

ansi = ["#241f31","#c01c28","#2ec27e","#f5c211","#1e78e4","#9841bb","#0ab9dc","#c0bfbc"]
brights = ["#5e5c64","#ed333b","#57e389","#f8e45c","#51a1ff","#c061cb","#4fd2fd","#f6f5f4"]
