# Havn Daggry
[colors]
foreground = "#3e4a77"
background = "#f8f9fb"
cursor_bg = "#386a51"
cursor_border = "#386a51"
cursor_fg = "#d7dbea"
selection_bg = "#d4e8de"
selection_fg = "#333c61"

ansi = ["#212840","#8f564b","#5c705b","#b36f00","#40567a","#775d93","#8a5a7e","#d7dbea"]
brights = ["#212840","#bd533e","#79957b","#f3b550","#6988bc","#7b7393","#a4879c","#d7dbea"]
