# starlight
[colors]
foreground = "#ffffff"
background = "#242424"
cursor_bg = "#ffffff"
cursor_border = "#ffffff"
cursor_fg = "#242424"
selection_bg = "#ffffff"
selection_fg = "#242424"

ansi = ["#242424","#e2425d","#66b238","#dec541","#54aad0","#e8b2f8","#5abf9b","#e6e6e6"]
brights = ["#616161","#ec5b58","#6bd162","#e9e85c","#78c3f3","#f2afee","#6adcc5","#ffffff"]
