# Terminal Basic Dark
[colors]
foreground = "#ffffff"
background = "#1d1e1d"
cursor_bg = "#9d9d9d"
cursor_border = "#9d9d9d"
cursor_fg = "#1d1e1d"
selection_bg = "#3f638a"
selection_fg = "#ffffff"

ansi = ["#000000","#c65339","#6ac44b","#b8b74a","#6444ed","#d357db","#69c1cf","#d1d1d1"]
brights = ["#909090","#eb5a3a","#77ea51","#efef53","#d09af9","#eb5af7","#78f1f2","#ededed"]
